name: Test Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    # Ensure there are no conflicting pushes to Codecov.
    concurrency:
      group: test-coverage
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Cargo tarpaulin
        run: cargo tarpaulin --out Xml
      - name: Upload the report to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
